DECIMAL_PLACES = 6
NUMBER_OF_COUNTS = 1000000
NUMBER_OF_CANDIDATES = 1000
# SOURCE_FILE = "../src/pmf.rs"
LIB_FILE = "../src/lib.rs"
RELEASE_FILE = "../target/release/density_evolution"
MUTATION_FACTOR = 0.8
KMAX = 4
# OFFSET = 10
DISPLAY = False
